development:
  adapter: postgresql
  encoding: unicode
  database: proficiency-test_development
  pool: 5
  username: postgres
  password: postgres  
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: proficiency-test_test
  pool: 5
  username: root
  password: "123"
    
production:  
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: educacao_production
  username: educacao
  password: <%= ENV['EDUCACAO_DATABASE_PASSWORD'] %>