development:
  adapter: postgresql
  encoding: unicode
  database: proficiency-test_development
  pool: 5
  username: postgres
  password: postgres  
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: proficiency-test_test
  pool: 5
  username: root
  password: "123"